In [44]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
arr.ndim


[[1 2 3]
 [4 5 6]]


2

In [45]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [46]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [47]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [48]:
print(arr)
arr**5  # x^5

[[1 2 3]
 [4 5 6]]


array([[   1,   32,  243],
       [1024, 3125, 7776]])

In [49]:
# an array of evenly spaced numbers
a = np.arange(24)
print(a)
print(a.ndim)

# now reshape it
b = a.reshape(2,3,4)
print(b)
print(b.ndim)
b = a.reshape(3,2,4)
print(b)
print(b.ndim)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
3


In [50]:
import numpy as np
arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print(arr[1,1])
print(arr[1][1])
print(arr[1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
5
[4 5 6]


In [51]:
print(arr[1:,1:])
# print any specific dimension metrix

print(arr[:2][1:])

[[5 6]
 [8 9]]
[[4 5 6]]


In [52]:
print(arr[1,:2])
print(arr[2,:1])

[4 5]
[7]


In [53]:
print(arr)

print(arr[:,0])
#you can find differencce between
print(arr[:,:1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 4 7]
[[1]
 [4]
 [7]]


In [54]:
print(arr[[2,1,0]])

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [55]:
names = np.array(['Aakash', 'Swara', 'Swaroop', 'Aakash', 'Swaroop', 'Swara', 'Swara'])
print(names)

print(names == 'Aakash')
print(names[names == 'Aakash'])  # its convert boolen to name

['Aakash' 'Swara' 'Swaroop' 'Aakash' 'Swaroop' 'Swara' 'Swara']
[ True False False  True False False False]
['Aakash' 'Aakash']
