1. Create a NumPy array with values from 1 to 10 and print the array.

In [25]:
import numpy as np
x1=np.arange(1,11)
print(x1)
x1

[ 1  2  3  4  5  6  7  8  9 10]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Create two NumPy arrays of size 5 and add them together.


In [26]:
x1=np.random.randint(100,1000,5)
x2=np.random.randint(100,1000,5)
print(x1)
print(x2)

x3=np.concatenate([x1,x2])
print(x3)

[391 161 364 982 666]
[236 714 577 207 668]
[391 161 364 982 666 236 714 577 207 668]


3. Create a 1D array of 12 elements and reshape it into a 3x4 matrix.

In [27]:
x1=np.random.randint(100,999,12)
x1.reshape(3,4)

array([[668, 584, 216, 897],
       [961, 512, 255, 181],
       [279, 260, 489, 724]])

4. Given the array arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]), slice and print the sub-array containing elements from index 3 to 6.

In [28]:
x1=np.array([1, 2, 3, 4, 5, 6, 7,8,9])
x1[3:7]

array([4, 5, 6, 7])

5. Create a NumPy array of size 5 and multiply each element by 2.

In [29]:
x1=np.array([1, 2, 3, 4, 5])
x1*2

array([ 2,  4,  6,  8, 10])

6. Create a NumPy array of 10 random numbers between 1 and 100. Then, calculate and print the mean and standard deviation of the array.

In [30]:
x1=np.random.randint(1,100,10)
print(x1)

print(x1.mean())
print(x1.std())

[48  6 38 74 30 99 96 79 48 90]
60.8
29.75836016987495


7. Create a 2x3 matrix and find its transpose.

In [50]:
x1=np.random.randn(2,3)
print(x1)
x1.T

[[ 0.8543227  -2.03128652 -2.62361406]
 [-0.50963183 -1.40655679 -0.43509823]]


array([[ 0.8543227 , -0.50963183],
       [-2.03128652, -1.40655679],
       [-2.62361406, -0.43509823]])

8. Create a 2D array of shape (3, 3) and add a 1D array [1, 2, 3] to it using broadcasting.

In [63]:
x1=np.random.randn(3,3)
print(x1)

x2=np.array([1, 2, 3])
print(x2)
x3=np.vstack([x1, x2])
print(x3)

[[-1.18975286  0.85666026  0.05065699]
 [-1.00934201 -0.2526999  -1.36572302]
 [ 0.65843257 -0.00900213 -0.03990366]]
[1 2 3]
[[-1.18975286  0.85666026  0.05065699]
 [-1.00934201 -0.2526999  -1.36572302]
 [ 0.65843257 -0.00900213 -0.03990366]
 [ 1.          2.          3.        ]]


9. Given the array arr = np.array([1, 2, 2, 3, 4, 4, 5]), find and print the unique elements in the array.

In [64]:
arr=np.array([1,2,2,3,4,4,5])
np.unique(arr)

array([1, 2, 3, 4, 5])

10. Create a NumPy array of size 6, and replace all values greater than 3 with the number 100.

11. Create two arrays arr1 = np.array([1, 2, 3]) and arr2 = np.array([4, 5, 6]). Stack them both vertically and horizontally.

 12. Create a 4x4 matrix. Using advanced indexing, extract the second column and the third row of the matrix.

13. Create two 3x3 matrices and multiply them using the dot product. Show both the matrix multiplication and the element-wise multiplication.

14. Generate a 3x3 matrix of random integers between 10 and 50, and a 2x5 matrix of random floats with values between 0 and 1.

15. Create a 3x3 matrix and add a scalar value 10 to each element of the matrix using broadcasting.

16. Standardize a NumPy array to have a mean of 0 and standard deviation of 1.

17. Generate an array of 10 evenly spaced numbers between 0 and 1 using np.linspace, and print the result.

18. Use np.linspace to create an array of 100 points between 0 and 2𝜋
, then compute the sine of these points and plot the result using Matplotlib.

19. Create a NumPy array arr = np.array([1, 2, 8, 4, 3]). Use argmax() to find the index of the maximum value in the array.

20. Create a NumPy array arr = np.array([5, 10, 2, 8, 3]). Use argmin() to find the index of the minimum value in the array.

21. Create a NumPy array arr = np.array([10, 20, 30, 40, 50]). Use Boolean indexing to select all values greater than 25.


22. Create a NumPy array arr = np.array([10, 15, 20, 25, 30, 35, 40]). Use Boolean indexing to select values that are greater than 15 but less than 35.

23. Create a NumPy array arr = np.array([1, 2, 3, 4, 5]). Use np.where() to replace all values greater than 3 with 10, and all other values with 0.

24. Create a NumPy array arr = np.array([12, 15, 18, 20, 22, 25]). Use np.where() to replace values greater than 20 with 10, values less than 15 with -10, and leave others unchanged.

25. Create a 2D array arr = np.array([[5, 10, 15], [2, 20, 30], [7, 1, 4]]). Use np.argmax() and np.argmin() to find the indices of the maximum and minimum values.