In [1]:
import numpy as np
arr=np.random.randn(8)
arr

array([ 1.41558053,  0.98423664, -0.72799128, -0.01527014,  0.12487159,
        1.4411013 ,  0.80882369, -1.32595022])

In [2]:
np.sign(arr)

array([ 1.,  1., -1., -1.,  1.,  1.,  1., -1.])

In [3]:
np.abs(arr)

array([1.41558053, 0.98423664, 0.72799128, 0.01527014, 0.12487159,
       1.4411013 , 0.80882369, 1.32595022])

In [4]:
x=np.random.randn(10)
y=np.random.randn(10)
print(x)
print(y)

[-0.03463125 -0.92185723 -0.78485013  1.55792738  0.76638169  0.27652096
 -0.20081582 -0.42822846 -0.05446174 -0.73500945]
[ 0.87283709  0.94472445 -0.46179294  0.91718646  0.12289762  0.71809736
 -0.8516304   0.82713606 -0.32331947  0.16949524]


In [5]:
np.maximum(x,y)

array([ 0.87283709,  0.94472445, -0.46179294,  1.55792738,  0.76638169,
        0.71809736, -0.20081582,  0.82713606, -0.05446174,  0.16949524])

In [6]:
x=np.array([1,2,3,4,5])
y=np.array([6,7,8,9,10])

np.minimum(x,y)

array([1, 2, 3, 4, 5])

In [7]:
arr=np.array([2,3,4,np.nan,5])
arr*2

array([ 4.,  6.,  8., nan, 10.])