In [2]:
import numpy as np
arr=np.random.randn(8)
arr

array([ 0.52783178, -0.28432924, -0.60165692, -0.5179436 , -0.96643184,
        0.48980835,  0.77101066,  2.08975059])

In [3]:
np.sign(arr)

array([ 1., -1., -1., -1., -1.,  1.,  1.,  1.])

In [4]:
np.abs(arr)

array([0.52783178, 0.28432924, 0.60165692, 0.5179436 , 0.96643184,
       0.48980835, 0.77101066, 2.08975059])

In [5]:
x=np.random.randn(10)
y=np.random.randn(10)
print(x)
print(y)

[ 0.70486169 -1.87119627  0.25916702  1.36755196 -0.63614686 -1.04232212
  0.66505512 -0.45045496  0.0433916  -0.80925914]
[-2.48597782  2.41686064 -0.19456769 -0.0229454  -1.22341699 -1.47259484
 -1.49699911  0.28176556 -0.88922247 -0.91371002]


In [6]:
np.maximum(x,y)

array([ 0.70486169,  2.41686064,  0.25916702,  1.36755196, -0.63614686,
       -1.04232212,  0.66505512,  0.28176556,  0.0433916 , -0.80925914])

In [7]:
x=np.array([1,2,3,4,5])
y=np.array([6,7,8,9,10])

np.minimum(x,y)

array([1, 2, 3, 4, 5])

In [8]:
arr=np.array([2,3,4,np.nan,5])
arr*2

array([ 4.,  6.,  8., nan, 10.])

In [9]:
arr = np.random.randn(100)

(arr > 0).sum() # Number of positive values

48

# Summation of only positive numbers in array.
np.where(arr < 0, 0, arr).sum()

44.50560783530728

44.50560783530728

In [10]:
arr=np.array([[3,1,7],[6,4,5]])
print(arr)
sortd_arr=np.sort(arr)
print(sortd_arr)

colmn_arr=np.sort(arr,axis=0)
print(colmn_arr)

[[3 1 7]
 [6 4 5]]
[[1 3 7]
 [4 5 6]]
[[3 1 5]
 [6 4 7]]


**Raw wise Descending**

In [11]:
darr=np.sort(arr,axis=1)[:,::-1]
print(darr)

[[7 3 1]
 [6 5 4]]


**Column wise Descending**

In [12]:
darr=np.sort(arr,axis=0)[:,::-1]
print(darr)

[[5 1 3]
 [7 4 6]]


In [13]:
arr=np.zeros((1,6,2,))
arr


array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [14]:
np.ravel(arr)
#ravel change dimension into one dim.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Linspace give us equle intervel number by defied range**

In [15]:
np.linspace(3,10,10)


array([ 3.        ,  3.77777778,  4.55555556,  5.33333333,  6.11111111,
        6.88888889,  7.66666667,  8.44444444,  9.22222222, 10.        ])

In [16]:
arr=np.array([[1,2,5,4,5],[7,5,4,2,5],[4,6,2,1,2]])
print(arr)

[[1 2 5 4 5]
 [7 5 4 2 5]
 [4 6 2 1 2]]


In [17]:
np.sum(arr,axis=0)

array([12, 13, 11,  7, 12])

In [18]:
np.sum(arr,axis=1)

array([17, 23, 15])

**We can print all array values by using flat whose make all values in flat line series**

In [19]:
x=arr.flat


In [20]:
for i in x:
    print(i)

1
2
5
4
5
7
5
4
2
5
4
6
2
1
2


In [21]:
arr=np.array([10,2,3,4,7,6,5,8,9,1])
print(arr[arr.argmax()])
print(arr.argmin())
#its give only max,min index position

10
9


In [22]:
print(arr.max())

10


**-------------------------------------------------------------------------------------------------------------------------------------------**

In [26]:
x=np.ones((4,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
x=np.arange(10,51)
x1=x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])