In [1]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
arr.ndim


[[1 2 3]
 [4 5 6]]


2

In [2]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [3]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [4]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [5]:
print(arr)
arr**5  # x^5

[[1 2 3]
 [4 5 6]]


array([[   1,   32,  243],
       [1024, 3125, 7776]])