In [1]:
import numpy as np
arr=np.random.randn(8)
arr

array([-1.06929045, -1.18563765,  0.00784208, -0.82936321, -1.3747808 ,
       -1.67071591, -1.81055885,  0.46827031])

In [2]:
np.sign(arr)

array([-1., -1.,  1., -1., -1., -1., -1.,  1.])

In [3]:
np.abs(arr)

array([1.06929045, 1.18563765, 0.00784208, 0.82936321, 1.3747808 ,
       1.67071591, 1.81055885, 0.46827031])

In [4]:
x=np.random.randn(10)
y=np.random.randn(10)
print(x)
print(y)

[ 0.0976248   0.46075383 -0.41033223  0.74011989  0.18843828  1.40830385
 -0.93486486  0.30634098 -0.48284857 -0.68200696]
[ 1.17806685 -0.34234881 -0.64687487 -0.64315954 -2.30293725 -0.94236966
  1.03271132 -2.20490304  1.35653267  0.10777507]


In [5]:
np.maximum(x,y)

array([ 1.17806685,  0.46075383, -0.41033223,  0.74011989,  0.18843828,
        1.40830385,  1.03271132,  0.30634098,  1.35653267,  0.10777507])

In [6]:
x=np.array([1,2,3,4,5])
y=np.array([6,7,8,9,10])

np.minimum(x,y)

array([1, 2, 3, 4, 5])

In [7]:
arr=np.array([2,3,4,np.nan,5])
arr*2

array([ 4.,  6.,  8., nan, 10.])

In [8]:
arr = np.random.randn(100)

(arr > 0).sum() # Number of positive values

48

# Summation of only positive numbers in array.
np.where(arr < 0, 0, arr).sum()

44.50560783530728

44.50560783530728

In [28]:
arr=np.array([[3,1,7],[6,4,5]])
print(arr)
sortd_arr=np.sort(arr)
print(sortd_arr)

colmn_arr=np.sort(arr,axis=0)
print(colmn_arr)

[[3 1 7]
 [6 4 5]]
[[1 3 7]
 [4 5 6]]
[[3 1 5]
 [6 4 7]]


**Raw wise Descending**

In [24]:
darr=np.sort(arr,axis=1)[:,::-1]
print(darr)

[[7 3 1]
 [6 5 4]]


**Column wise Descending**

In [26]:
darr=np.sort(arr,axis=0)[:,::-1]
print(darr)

[[5 1 3]
 [7 4 6]]
