In [19]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
arr.ndim


[[1 2 3]
 [4 5 6]]


2

In [20]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [21]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [22]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [23]:
print(arr)
arr**5  # x^5

[[1 2 3]
 [4 5 6]]


array([[   1,   32,  243],
       [1024, 3125, 7776]])

In [24]:
# an array of evenly spaced numbers
a = np.arange(24)
print(a)
print(a.ndim)

# now reshape it
b = a.reshape(2,3,4)
print(b)
print(b.ndim)
b = a.reshape(3,2,4)
print(b)
print(b.ndim)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
3
