In [71]:
import numpy as np
x=[4,4,5,1,5,5]
x1=np.array(x)
print(x)
print(x1)
print(type(x1))

[4, 4, 5, 1, 5, 5]
[4 4 5 1 5 5]
<class 'numpy.ndarray'>


In [72]:
x2=x1*9/5+32  #Numpy is not contains coma(,)
print(x2)

[39.2 39.2 41.  33.8 41.  41. ]


In [73]:

x1=np.array([1,2,3,6,5])
x1

array([1, 2, 3, 6, 5])

In [74]:

x1=np.array([1,2,3,6,5],ndmin=2)
print(x1)
print(x1.shape)

[[1 2 3 6 5]]
(1, 5)


In [75]:
x=[4,4,5,1,5,'a']
x1=np.array(x)
print(x1)


['4' '4' '5' '1' '5' 'a']


In [76]:
import numpy as np
x=np.dtype([('Name','S20'),('Age','i1'),('marks','f4')])
x

dtype([('Name', 'S20'), ('Age', 'i1'), ('marks', '<f4')])

In [77]:
a=np.array([('Sunil',21,45),('Anil',41,88)],dtype=x)
a

array([(b'Sunil', 21, 45.), (b'Anil', 41, 88.)],
      dtype=[('Name', 'S20'), ('Age', 'i1'), ('marks', '<f4')])

In [78]:

#a.shape=
#x1=a.reshape(2,4)

In [79]:
a=np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [80]:
b=a.reshape(2,4,3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [81]:
import numpy as np
x1=np.arange(24)
x2=np.array(x1)
print(x2)
print(type(x2))
print(x2.size)
print(x2.shape)
print(x2.ndim)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
<class 'numpy.ndarray'>
24
(24,)
1


In [82]:

x4=x2[::2]
print(x4)
x2.ndim

[ 0  2  4  6  8 10 12 14 16 18 20 22]


1

In [83]:
v1=x2.reshape(2,4,3)
print(v1)
print(v1.shape)
print(v1.ndim)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
(2, 4, 3)
3


In [84]:
x2=np.arange(40)
v2=x2.reshape(2,2,2,5)
print(v2)

[[[[ 0  1  2  3  4]
   [ 5  6  7  8  9]]

  [[10 11 12 13 14]
   [15 16 17 18 19]]]


 [[[20 21 22 23 24]
   [25 26 27 28 29]]

  [[30 31 32 33 34]
   [35 36 37 38 39]]]]


In [85]:
x2=np.array([1,2,3,4,5,6],dtype=np.int8)
print(x2)

[1 2 3 4 5 6]


In [86]:
x2=np.array([1,2,3,4,5,6],dtype=np.float32)
print(x2)

[1. 2. 3. 4. 5. 6.]


In [90]:
print(x2.flags['WRITEABLE'])
x2.flags['WRITEABLE']=False
x2[2]=12


False


ValueError: assignment destination is read-only

In [95]:
x=np.zeros(5)
print(x)
x=np.zero(5,dtype=int8)

[0. 0. 0. 0. 0.]


AttributeError: module 'numpy' has no attribute 'zero'

In [101]:
x=np.arange(10,20,2,dtype=float)
print(x)


[10. 12. 14. 16. 18.]


In [106]:
x=np.linspace(10,20,5,endpoint=False,retstep=True)
print(x)

#(endpoint-start)/(n-1) if endpoint=True

#if endpoint=False then (stop-start)/(num)

(array([10., 12., 14., 16., 18.]), 2.0)
