In [63]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
arr.ndim


[[1 2 3]
 [4 5 6]]


2

In [64]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [65]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [66]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [67]:
print(arr)
arr**5  # x^5

[[1 2 3]
 [4 5 6]]


array([[   1,   32,  243],
       [1024, 3125, 7776]])

In [68]:
# an array of evenly spaced numbers
a = np.arange(24)
print(a)
print(a.ndim)

# now reshape it
b = a.reshape(2,3,4)
print(b)
print(b.ndim)
b = a.reshape(3,2,4)
print(b)
print(b.ndim)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
3


In [69]:
import numpy as np
arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print(arr[1,1])
print(arr[1][1])
print(arr[1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
5
[4 5 6]


In [70]:
print(arr[1:,1:])
# print any specific dimension metrix

print(arr[:2][1:])

[[5 6]
 [8 9]]
[[4 5 6]]


In [71]:
print(arr[1,:2])
print(arr[2,:1])

[4 5]
[7]


In [72]:
print(arr)

print(arr[:,0])
#you can find differencce between
print(arr[:,:1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 4 7]
[[1]
 [4]
 [7]]


In [73]:
print(arr[[2,1,0]])

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [74]:
names = np.array(['Aakash', 'Swara', 'Swaroop', 'Aakash', 'Swaroop', 'Swara', 'Swara'])
print(names)

print(names == 'Aakash')
print(names[names == 'Aakash'])  # its convert boolen to name

['Aakash' 'Swara' 'Swaroop' 'Aakash' 'Swaroop' 'Swara' 'Swara']
[ True False False  True False False False]
['Aakash' 'Aakash']


In [75]:
data=np.random.randn(20,3)
print(data)

print(data>=0)

print(data[data>=0])

[[-4.61309263e-01 -1.65411719e+00 -2.49129437e-01]
 [-1.07063733e+00  3.25792933e-01  4.50261114e-01]
 [ 6.29338898e-01  7.11680800e-02  2.92370175e-01]
 [ 1.81255019e-01  6.88038574e-01  8.11055244e-01]
 [ 1.89078942e+00 -8.19222497e-01 -1.12283745e-01]
 [-1.28093412e-01 -9.06641922e-01 -3.64833420e-01]
 [-1.16056915e-01 -2.26595373e-01 -5.25247619e-01]
 [ 2.51994285e-01  1.20384336e+00 -9.46152959e-01]
 [-5.97476628e-01  6.95440915e-01  2.02042938e+00]
 [ 1.23028167e+00 -7.53734473e-01  1.05854029e+00]
 [ 7.08067261e-01  1.41209243e+00 -3.94728722e-02]
 [ 8.94640915e-01  1.75452615e+00 -1.39805762e-01]
 [-1.49452856e+00  1.48436978e-01  1.90374937e+00]
 [ 1.29586124e+00 -1.34683615e+00  1.58106752e+00]
 [-4.88000740e-01  8.56860466e-01  1.54376801e+00]
 [ 5.57796362e-01 -2.84608947e-01 -9.22800970e-01]
 [ 7.96724305e-01 -2.00377062e+00 -5.32208506e-01]
 [ 1.13709386e+00 -1.07352267e+00  9.26677793e-01]
 [-1.35198121e+00 -1.61671978e-03  2.27008575e-01]
 [ 4.99673567e-01 -1.54611426e-

In [78]:
data[data<0]=0
print(data)

[[0.         0.         0.        ]
 [0.         0.32579293 0.45026111]
 [0.6293389  0.07116808 0.29237018]
 [0.18125502 0.68803857 0.81105524]
 [1.89078942 0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.25199428 1.20384336 0.        ]
 [0.         0.69544091 2.02042938]
 [1.23028167 0.         1.05854029]
 [0.70806726 1.41209243 0.        ]
 [0.89464091 1.75452615 0.        ]
 [0.         0.14843698 1.90374937]
 [1.29586124 0.         1.58106752]
 [0.         0.85686047 1.54376801]
 [0.55779636 0.         0.        ]
 [0.7967243  0.         0.        ]
 [1.13709386 0.         0.92667779]
 [0.         0.         0.22700857]
 [0.49967357 0.         0.        ]]
