## Series

In [1]:
import pandas as pd
import numpy as np

In [2]:
x1=pd.Series(dtype=float)
print(x1)

Series([], dtype: float64)


In [3]:
import numpy as np
series=np.array([1,2,3,4,5])
x1=pd.Series(series,dtype=float,index=['a','b','c','d','e'])
print(x1)

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64


In [4]:
print(x1[:5])
print(x1[:5])
print(x1[::-1])
print(x1[:-5:-1])
#sequence[start:stop:step]


a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64
a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64
e    5.0
d    4.0
c    3.0
b    2.0
a    1.0
dtype: float64
e    5.0
d    4.0
c    3.0
b    2.0
dtype: float64


In [5]:
print(x1.axes)
print(x1.empty)

print(x1.size)
print(len(x1))
x1.values

[Index(['a', 'b', 'c', 'd', 'e'], dtype='object')]
False
5
5


array([1., 2., 3., 4., 5.])

In [6]:
data={'a':45,'b':12,'c':75}
x1=pd.Series(data,index=['a','b','c','d'])
print(x1)

a    45.0
b    12.0
c    75.0
d     NaN
dtype: float64


In [7]:
data=pd.Series(5,index=['a','b','c','d'],dtype=float)
print(data)

a    5.0
b    5.0
c    5.0
d    5.0
dtype: float64


In [8]:
x1=pd.Series(np.random.rand(5))
x1

0    0.326249
1    0.139405
2    0.083177
3    0.199311
4    0.629100
dtype: float64

In [9]:
x1=x1.set_axis([4,5,25,4,45])
x1

4     0.326249
5     0.139405
25    0.083177
4     0.199311
45    0.629100
dtype: float64

In [10]:
print(x1.head(2))
print(x1.tail(2))

4    0.326249
5    0.139405
dtype: float64
4     0.199311
45    0.629100
dtype: float64


In [11]:
x2=x1.copy
print(x2)

<bound method NDFrame.copy of 4     0.326249
5     0.139405
25    0.083177
4     0.199311
45    0.629100
dtype: float64>


## DataFrame

In [12]:
#List
a=[[1,2],[45,12]]
b=pd.DataFrame(a,columns=['A','B'],index=['a','b'])
print(b)

    A   B
a   1   2
b  45  12


In [13]:
print(b.columns)
print(b.index)

Index(['A', 'B'], dtype='object')
Index(['a', 'b'], dtype='object')


In [14]:
x1=[{'a':4,'b':5},{'A':78,'b':6,'a':45 }]
x2=pd.DataFrame(x1)
x2

a  b     A
0   4  5   NaN
1  45  6  78.0

In [15]:
x2.empty
x2.set_axis(['A','B'],axis=0)

a  b     A
A   4  5   NaN
B  45  6  78.0

In [16]:
print(x2)
print(x2.reindex(columns=['b','a']))

    a  b     A
0   4  5   NaN
1  45  6  78.0
   b   a
0  5   4
1  6  45


In [17]:
# DataFrame from Series

a1={'one':pd.Series([1,2,3],index=['a','b','c']),
    'two':pd.Series([4,6],index=['a','c'])}

a2=pd.DataFrame(a1)
print(a2)

   one  two
a    1  4.0
b    2  NaN
c    3  6.0


In [18]:
x1=pd.DataFrame(np.arange(10).reshape(5,2),index=['a','b','c','d','e'],columns=['A','B'])
print(x1)

   A  B
a  0  1
b  2  3
c  4  5
d  6  7
e  8  9


In [19]:
print(x1[['A']])
print(x1[['A','B']])

   A
a  0
b  2
c  4
d  6
e  8
   A  B
a  0  1
b  2  3
c  4  5
d  6  7
e  8  9


In [20]:
print(x1.loc['b'])
print(x1.loc['b','A'])
print(x1.loc['a':'d'])
print(x1.loc['a':'d',['A']])

A    2
B    3
Name: b, dtype: int32
2
   A  B
a  0  1
b  2  3
c  4  5
d  6  7
   A
a  0
b  2
c  4
d  6


In [21]:
print(
    x1.loc[x1['A']>2]
)

   A  B
c  4  5
d  6  7
e  8  9


In [22]:
x1.loc[x1['A']>2]=5
print(x1)

   A  B
a  0  1
b  2  3
c  5  5
d  5  5
e  5  5


In [23]:
print(x1.iloc[4])
print(x1.iloc[4,1])
print(x1.iloc[1:4])
print(x1.iloc[1:4,1])
print(x1.iloc[1:4,0:2])

A    5
B    5
Name: e, dtype: int32
5
   A  B
b  2  3
c  5  5
d  5  5
b    3
c    5
d    5
Name: B, dtype: int32
   A  B
b  2  3
c  5  5
d  5  5


In [24]:
print(x1)
x1['C']=pd.Series([4,5,2,5,4],
                  index=['a','b','c','d','e'])

print(x1)

   A  B
a  0  1
b  2  3
c  5  5
d  5  5
e  5  5
   A  B  C
a  0  1  4
b  2  3  5
c  5  5  2
d  5  5  5
e  5  5  4


In [25]:
x1['A+B']=x1['A']+x1['B']
print(x1)

   A  B  C  A+B
a  0  1  4    1
b  2  3  5    5
c  5  5  2   10
d  5  5  5   10
e  5  5  4   10


In [26]:
x1.drop(columns=['A+B'])
x1.pop('C')
x1.drop(index='b') # by default choose rows
#also we can use axis=1 inplace of columns
# drop may use for droping rows and its create a new object not inplace

A  B  A+B
a  0  1    1
c  5  5   10
d  5  5   10
e  5  5   10

In [27]:
f1=pd.DataFrame([[1,2,3],[1,2,3]],columns=['A','B','C'])
f2=pd.DataFrame([[1,2,3],[1,2,3]],columns=['A','B','C'])

In [28]:
x2=pd.concat([f1,f2],ignore_index=True)
print(x2)

   A  B  C
0  1  2  3
1  1  2  3
2  1  2  3
3  1  2  3


In [29]:
print(x2.dtypes)
print(x2.shape)
print(x2.ndim)
print(x2.size)
print(x2.values)
print(x2.empty)

A    int64
B    int64
C    int64
dtype: object
(4, 3)
2
12
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
False


# Re-indexing = Rearanging rows and columns Not updating

In [30]:
c1=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(c1)
print(c1.reindex(['a','b','c','e','d']))

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
b    2
c    3
e    5
d    4
dtype: int64


In [31]:
obj1=pd.Series(['Aam','Ram','Saam'],index=[0,2,4])
obj1

0     Aam
2     Ram
4    Saam
dtype: object

In [32]:
print(obj1.reindex(range(6)))
print(obj1.reindex(range(6)).ffill())
print(obj1.reindex(range(6),method='bfill'))


0     Aam
1     NaN
2     Ram
3     NaN
4    Saam
5     NaN
dtype: object
0     Aam
1     Aam
2     Ram
3     Ram
4    Saam
5    Saam
dtype: object
0     Aam
1     Ram
2     Ram
3    Saam
4    Saam
5     NaN
dtype: object


In [33]:
# Pop can use for series and dataframe both
print(x2)
x2.drop([1,2],axis=0) # by default take rows
print(x2.drop(['A','B'],axis=1))
print(x2.drop(['A','B'],axis='columns',inplace=True))
# Basically inplace used to change objects 

   A  B  C
0  1  2  3
1  1  2  3
2  1  2  3
3  1  2  3
   C
0  3
1  3
2  3
3  3
None


In [34]:
print(x2)

   C
0  3
1  3
2  3
3  3


In [35]:
df=pd.DataFrame(np.arange(12).reshape(3,4),columns=['A','B','C','D'])
df

A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [36]:
df.set_axis(['a','b','c'],axis=0)
#same things= df.set_axis(['a','b','c'],axis='index')

A  B   C   D
a  0  1   2   3
b  4  5   6   7
c  8  9  10  11

In [37]:
df.set_axis(['D','B','C','A'],axis=1)

D  B   C   A
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [38]:
df.set_index('D',inplace=True)
df

A  B   C
D           
3   0  1   2
7   4  5   6
11  8  9  10

In [39]:
df.reset_index(inplace=True)
df

D  A  B   C
0   3  0  1   2
1   7  4  5   6
2  11  8  9  10

In [40]:
# make a row as a column

df.columns=df.iloc[0]
df

0   3  0  1   2
0   3  0  1   2
1   7  4  5   6
2  11  8  9  10

In [41]:
import pandas as pd

s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
print(s1)

s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])
print(s2)

result = s1 + s2
result


a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64
a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64


a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [42]:
''' For
addition if column or index lables not meet same then
NaN will be the result
'''

' For\naddition if column or index lables not meet same then\nNaN will be the result\n'

In [43]:
df1 = pd.DataFrame(np.arange(12).reshape(3, 4), columns=list('abcd'))
df1


a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [44]:
df2 = pd.DataFrame(np.arange(20).reshape(4, 5), columns=list('abcde'))
df2.loc[1, 'b'] = np.nan
df2


a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [45]:
df1 + df2


a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [46]:
df3= df1.add(df2,fill_value=0)
df3

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [47]:
len(df3)

4

In [48]:
df3.loc[1]=[0,0,0,0,0]
df3

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   0.0   0.0   0.0   0.0   0.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [49]:
df3.loc[len(df3)]=[1,1,1,1,1]
df3

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   0.0   0.0   0.0   0.0   0.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0
4   1.0   1.0   1.0   1.0   1.0

In [50]:
df3.loc[2,'b']=25
print(df3)

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   0.0   0.0   0.0   0.0   0.0
2  18.0  25.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0
4   1.0   1.0   1.0   1.0   1.0


## Apply with Function

In [51]:
f= lambda x:x.max()-x.min()
print(df3.apply(f,axis=0))
print(df3.apply(f,axis=1))

a    18.0
b    25.0
c    22.0
d    24.0
e    19.0
dtype: float64
0     6.0
1     0.0
2    11.0
3     4.0
4     0.0
dtype: float64


In [52]:
df = pd.DataFrame({
    'Name': pd.Series(['abby', 'bobby', 'cape', 'danny', 'rocky', 'vicky'], index=[1, 2, 3, 4, 5, 6]),
    'age': pd.Series([30, 32, 31, 36, 27, 29], index=[1, 2, 3, 4, 5, 6]),
    'Marks': pd.Series([176, 175, '174', 177, 179, 186], index=[1, 2, 3, 4, 5, 6])
})
df

Name  age Marks
1   abby   30   176
2  bobby   32   175
3   cape   31   174
4  danny   36   177
5  rocky   27   179
6  vicky   29   186

In [53]:
df.dtypes

Name     object
age       int64
Marks    object
dtype: object

In [54]:
df['Marks']=df['Marks'].astype(int)

In [55]:
df['Percent']=(df['Marks']/200)*100
print(df)

    Name  age  Marks  Percent
1   abby   30    176     88.0
2  bobby   32    175     87.5
3   cape   31    174     87.0
4  danny   36    177     88.5
5  rocky   27    179     89.5
6  vicky   29    186     93.0


In [56]:
df.dtypes

Name        object
age          int64
Marks        int32
Percent    float64
dtype: object

In [57]:
df['Percent']=df['Percent'].astype(int)
df.dtypes

Name       object
age         int64
Marks       int32
Percent     int32
dtype: object

In [58]:
print(df)

    Name  age  Marks  Percent
1   abby   30    176       88
2  bobby   32    175       87
3   cape   31    174       87
4  danny   36    177       88
5  rocky   27    179       89
6  vicky   29    186       93


In [59]:
import pandas as pd

# Create a DataFrame with a column containing numeric strings and invalid entries
df1 = pd.DataFrame({'A': ['1', '2', 'invalid']})
print("Original DataFrame:")
print(df1)

# Convert column 'A' to numeric, replacing invalid values with NaN
df1['A'] = pd.to_numeric(df1['A'], errors='coerce')
print("\nDataFrame after converting 'A' to numeric:")
print(df1)


Original DataFrame:
         A
0        1
1        2
2  invalid

DataFrame after converting 'A' to numeric:
     A
0  1.0
1  2.0
2  NaN


In [60]:
# Create a DataFrame with a column containing date strings
df = pd.DataFrame({'date': ['2024-11-21', '2024-11-22']})
print("\nOriginal DataFrame with dates:")
print(df)
print(df.dtypes)

# Convert column 'date' to datetime
df['date'] = pd.to_datetime(df['date'])
print("\nDataFrame after converting 'date' to datetime:")
print(df)

# Check the data types
print("\nData types of the DataFrame:")
print(df.dtypes)



Original DataFrame with dates:
         date
0  2024-11-21
1  2024-11-22
date    object
dtype: object

DataFrame after converting 'date' to datetime:
        date
0 2024-11-21
1 2024-11-22

Data types of the DataFrame:
date    datetime64[ns]
dtype: object


In [61]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       2 non-null      float64
dtypes: float64(1)
memory usage: 156.0 bytes
