## Series

In [31]:
import pandas as pd
import numpy as np

In [32]:
x1=pd.Series(dtype=float)
print(x1)

Series([], dtype: float64)


In [33]:
import numpy as np
series=np.array([1,2,3,4,5])
x1=pd.Series(series,dtype=float,index=['a','b','c','d','e'])
print(x1)

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64


In [34]:
print(x1[:5])
print(x1[:5])
print(x1[::-1])
print(x1[:-5:-1])
#sequence[start:stop:step]


a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64
a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64
e    5.0
d    4.0
c    3.0
b    2.0
a    1.0
dtype: float64
e    5.0
d    4.0
c    3.0
b    2.0
dtype: float64


In [35]:
print(x1.axes)
print(x1.empty)

print(x1.size)
print(len(x1))
x1.values

[Index(['a', 'b', 'c', 'd', 'e'], dtype='object')]
False
5
5


array([1., 2., 3., 4., 5.])

In [36]:
data={'a':45,'b':12,'c':75}
x1=pd.Series(data,index=['a','b','c','d'])
print(x1)

a    45.0
b    12.0
c    75.0
d     NaN
dtype: float64


In [37]:
data=pd.Series(5,index=['a','b','c','d'],dtype=float)
print(data)

a    5.0
b    5.0
c    5.0
d    5.0
dtype: float64


In [38]:
x1=pd.Series(np.random.rand(5))
x1

0    0.763506
1    0.425126
2    0.216467
3    0.826360
4    0.726107
dtype: float64

In [39]:
x1=x1.set_axis([4,5,25,4,45])
x1

4     0.763506
5     0.425126
25    0.216467
4     0.826360
45    0.726107
dtype: float64

In [40]:
print(x1.head(2))
print(x1.tail(2))

4    0.763506
5    0.425126
dtype: float64
4     0.826360
45    0.726107
dtype: float64


In [41]:
x2=x1.copy
print(x2)

<bound method NDFrame.copy of 4     0.763506
5     0.425126
25    0.216467
4     0.826360
45    0.726107
dtype: float64>


## DataFrame

In [42]:
#List
a=[[1,2],[45,12]]
b=pd.DataFrame(a,columns=['A','B'],index=['a','b'])
print(b)

    A   B
a   1   2
b  45  12


In [43]:
print(b.columns)
print(b.index)

Index(['A', 'B'], dtype='object')
Index(['a', 'b'], dtype='object')


In [44]:
x1=[{'a':4,'b':5},{'A':78,'b':6,'a':45 }]
x2=pd.DataFrame(x1)
x2

a  b     A
0   4  5   NaN
1  45  6  78.0

In [45]:
x2.empty
x2.set_axis(['A','B'],axis=0)

a  b     A
A   4  5   NaN
B  45  6  78.0

In [46]:
print(x2)
print(x2.reindex(columns=['b','a']))

    a  b     A
0   4  5   NaN
1  45  6  78.0
   b   a
0  5   4
1  6  45


In [47]:
# DataFrame from Series

a1={'one':pd.Series([1,2,3],index=['a','b','c']),
    'two':pd.Series([4,6],index=['a','c'])}

a2=pd.DataFrame(a1)
print(a2)

   one  two
a    1  4.0
b    2  NaN
c    3  6.0


In [48]:
x1=pd.DataFrame(np.arange(10).reshape(5,2),index=['a','b','c','d','e'],columns=['A','B'])
print(x1)

   A  B
a  0  1
b  2  3
c  4  5
d  6  7
e  8  9


In [49]:
print(x1[['A']])
print(x1[['A','B']])

   A
a  0
b  2
c  4
d  6
e  8
   A  B
a  0  1
b  2  3
c  4  5
d  6  7
e  8  9


In [50]:
print(x1.loc['b'])
print(x1.loc['b','A'])
print(x1.loc['a':'d'])
print(x1.loc['a':'d',['A']])

A    2
B    3
Name: b, dtype: int32
2
   A  B
a  0  1
b  2  3
c  4  5
d  6  7
   A
a  0
b  2
c  4
d  6


In [51]:
print(
    x1.loc[x1['A']>2]
)

   A  B
c  4  5
d  6  7
e  8  9


In [52]:
x1.loc[x1['A']>2]=5
print(x1)

   A  B
a  0  1
b  2  3
c  5  5
d  5  5
e  5  5


In [53]:
print(x1.iloc[4])
print(x1.iloc[4,1])
print(x1.iloc[1:4])
print(x1.iloc[1:4,1])
print(x1.iloc[1:4,0:2])

A    5
B    5
Name: e, dtype: int32
5
   A  B
b  2  3
c  5  5
d  5  5
b    3
c    5
d    5
Name: B, dtype: int32
   A  B
b  2  3
c  5  5
d  5  5


In [54]:
print(x1)
x1['C']=pd.Series([4,5,2,5,4],
                  index=['a','b','c','d','e'])

print(x1)

   A  B
a  0  1
b  2  3
c  5  5
d  5  5
e  5  5
   A  B  C
a  0  1  4
b  2  3  5
c  5  5  2
d  5  5  5
e  5  5  4


In [55]:
x1['A+B']=x1['A']+x1['B']
print(x1)

   A  B  C  A+B
a  0  1  4    1
b  2  3  5    5
c  5  5  2   10
d  5  5  5   10
e  5  5  4   10


In [56]:
x1.drop(columns=['A+B'])
x1.pop('C')
x1.drop(index='b') # by default choose rows
#also we can use axis=1 inplace of columns
# drop may use for droping rows and its create a new object not inplace

A  B  A+B
a  0  1    1
c  5  5   10
d  5  5   10
e  5  5   10

In [57]:
f1=pd.DataFrame([[1,2,3],[1,2,3]],columns=['A','B','C'])
f2=pd.DataFrame([[1,2,3],[1,2,3]],columns=['A','B','C'])

In [58]:
x2=pd.concat([f1,f2],ignore_index=True)
print(x2)

   A  B  C
0  1  2  3
1  1  2  3
2  1  2  3
3  1  2  3


In [59]:
print(x2.dtypes)
print(x2.shape)
print(x2.ndim)
print(x2.size)
print(x2.values)
print(x2.empty)

A    int64
B    int64
C    int64
dtype: object
(4, 3)
2
12
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
False


# Re-indexing = Rearanging rows and columns Not updating

In [60]:
c1=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(c1)
print(c1.reindex(['a','b','c','e','d']))

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
b    2
c    3
e    5
d    4
dtype: int64
