In [2]:
import numpy as np
arr=np.random.randn(8)
arr

array([ 1.34826886,  0.55419118, -2.4243663 ,  0.8846962 , -1.31717311,
        0.46187774, -0.76687932, -0.41883341])

In [3]:
np.sign(arr)

array([ 1.,  1., -1.,  1., -1.,  1., -1., -1.])

In [4]:
np.abs(arr)

array([1.34826886, 0.55419118, 2.4243663 , 0.8846962 , 1.31717311,
       0.46187774, 0.76687932, 0.41883341])

In [5]:
x=np.random.randn(5)
y=np.random.randn(5)
print(x)
print(y)

[-1.08789963 -0.5798498   0.79126724 -1.46466535  0.40458862]
[-0.28869135  1.27235536  1.21164438 -0.39806897 -0.90370446]


In [6]:
np.maximum(x,y)

array([-0.28869135,  1.27235536,  1.21164438, -0.39806897,  0.40458862])

In [7]:
x=np.array([1,2,3,4,5])
y=np.array([6,7,8,9,10])

np.minimum(x,y)

array([1, 2, 3, 4, 5])

In [8]:
arr=np.array([2,3,4,np.nan,5])
arr*2

array([ 4.,  6.,  8., nan, 10.])

In [9]:
arr = np.random.randn(100)

(arr > 0).sum() # Number of positive values

48

# Summation of only positive numbers in array.
np.where(arr < 0, 0, arr).sum()

44.50560783530728

44.50560783530728

In [10]:
arr=np.array([[3,1,7],[6,4,5]])
print(arr)
sortd_arr=np.sort(arr)
print(sortd_arr)

colmn_arr=np.sort(arr,axis=0)
print(colmn_arr)

[[3 1 7]
 [6 4 5]]
[[1 3 7]
 [4 5 6]]
[[3 1 5]
 [6 4 7]]


**Raw wise Descending**

In [11]:
darr=np.sort(arr,axis=1)[:,::-1]
print(darr)

[[7 3 1]
 [6 5 4]]


**Column wise Descending**

In [12]:
darr=np.sort(arr,axis=0)[:,::-1]
print(darr)

[[5 1 3]
 [7 4 6]]


In [13]:
arr=np.zeros((1,6,2))
arr


array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [14]:
np.ravel(arr)
#ravel change dimension into one dim.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Linspace give us equle intervel number by defied range**

In [15]:
np.linspace(3,10,10)


array([ 3.        ,  3.77777778,  4.55555556,  5.33333333,  6.11111111,
        6.88888889,  7.66666667,  8.44444444,  9.22222222, 10.        ])

In [16]:
arr=np.array([[1,2,5,4,5],[7,5,4,2,5],[4,6,2,1,2]])
print(arr)

[[1 2 5 4 5]
 [7 5 4 2 5]
 [4 6 2 1 2]]


In [17]:
np.sum(arr,axis=0)

array([12, 13, 11,  7, 12])

In [18]:
np.sum(arr,axis=1)

array([17, 23, 15])

**We can print all array values by using flat whose make all values in flat line series**

In [19]:
x=arr.flat


In [20]:
for i in x:
    print(i)

1
2
5
4
5
7
5
4
2
5
4
6
2
1
2


In [42]:
arr=np.array([10,2,3,4,7,6,5,8,9,1])
print(arr[arr.argmax()])
print(arr[arr.argmin()])
#its give only max,min index position

10
1


In [22]:
print(arr.max())

10


**-------------------------------------------------------------------------------------------------------------------------------------------**

In [23]:
x=np.ones((4,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
x=np.arange(10,51)
x1=x

In [25]:
arr=np.random.randint(0,21,size=5) # the give random number generator between 0 and 21 total random 5
arr

array([12,  8,  6, 14,  6], dtype=int32)

In [26]:
arr=np.random.randint(0,10)
arr

2

In [27]:
arr=np.random.randint(0,11,size=(3,3))
arr

array([[ 3,  7, 10],
       [ 4,  6,  2],
       [ 9,  5,  0]], dtype=int32)

In [40]:
arr1=np.random.randint(0,11,size=(1,8))
arr3=np.random.randint(0,11,size=(1,8))
arr2=np.random.randint(0,11,size=(1,8))
print(arr1)
print(arr2)
print(arr3)


# its mandadory to run broadcating with same size of metrix and arrays

[[ 2  9  3 10  6  2  9  3]]
[[3 3 0 3 8 7 5 3]]
[[ 9  1  6  9 10  2 10  9]]
