In [1]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
arr.ndim


[[1 2 3]
 [4 5 6]]


2

In [2]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [3]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [4]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [5]:
print(arr)
arr**5  # x^5

[[1 2 3]
 [4 5 6]]


array([[   1,   32,  243],
       [1024, 3125, 7776]])

In [6]:
# an array of evenly spaced numbers
a = np.arange(24)
print(a)
print(a.ndim)

# now reshape it
b = a.reshape(2,3,4)
print(b)
print(b.ndim)
b = a.reshape(3,2,4)
print(b)
print(b.ndim)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
3


In [7]:
import numpy as np
arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print(arr[1,1])
print(arr[1][1])
print(arr[1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
5
[4 5 6]


In [8]:
print(arr[1:,1:])
# print any specific dimension metrix

print(arr[:2][1:])

[[5 6]
 [8 9]]
[[4 5 6]]


In [9]:
print(arr[1,:2])
print(arr[2,:1])

[4 5]
[7]


In [10]:
print(arr)

print(arr[:,0])
#you can find differencce between
print(arr[:,:1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 4 7]
[[1]
 [4]
 [7]]


In [11]:
print(arr[[2,1,0]])

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [12]:
names = np.array(['Aakash', 'Swara', 'Swaroop', 'Aakash', 'Swaroop', 'Swara', 'Swara'])
print(names)

print(names == 'Aakash')
print(names[names == 'Aakash'])  # its convert boolen to name

['Aakash' 'Swara' 'Swaroop' 'Aakash' 'Swaroop' 'Swara' 'Swara']
[ True False False  True False False False]
['Aakash' 'Aakash']


In [13]:
print(names[names!='Aakash'])

['Swara' 'Swaroop' 'Swaroop' 'Swara' 'Swara']


In [14]:
x1= (names=='Aakash')|(names=='Swara')
print(x1)

[ True  True False  True False  True  True]


In [15]:
names[names!='Aakash'] ='as'
print(names)

['Aakash' 'as' 'as' 'Aakash' 'as' 'as' 'as']


In [16]:
data=np.random.randn(20,3)
print(data)

print(data>=0)

print(data[data>=0])

[[ 0.98805966 -2.07749005 -0.20787109]
 [ 0.3496726  -2.67133296  0.08871361]
 [-0.23135317 -0.61341866 -1.37933357]
 [ 2.77712215  0.06577697 -0.09164173]
 [-1.22655338  0.04518842  0.07919559]
 [ 0.25645059  0.01154017 -0.2881682 ]
 [ 1.67235792 -2.65967637 -2.16870527]
 [-0.94250651  0.81116558 -1.51270316]
 [ 0.79256524 -1.58932214 -0.58151404]
 [ 1.03781913  1.76693437 -0.29156997]
 [-0.2457095   0.72310602  0.8392368 ]
 [ 0.50389845 -0.24272376 -0.84137074]
 [-1.06189265 -0.78793308  0.87100308]
 [-0.34916782 -0.92846294  0.71410833]
 [-0.11872692 -1.4504602   1.91907899]
 [ 0.29084097  1.27046649 -1.92141485]
 [-0.2674425   1.07364684 -0.54375513]
 [ 0.08984546  0.56398505  0.38222671]
 [ 0.75045001  0.42510528  0.88144098]
 [ 0.5933376   0.45860744  0.36628793]]
[[ True False False]
 [ True False  True]
 [False False False]
 [ True  True False]
 [False  True  True]
 [ True  True False]
 [ True False False]
 [False  True False]
 [ True False False]
 [ True  True False]
 [False  

In [17]:
data[data<0]=0
print(data)

[[0.98805966 0.         0.        ]
 [0.3496726  0.         0.08871361]
 [0.         0.         0.        ]
 [2.77712215 0.06577697 0.        ]
 [0.         0.04518842 0.07919559]
 [0.25645059 0.01154017 0.        ]
 [1.67235792 0.         0.        ]
 [0.         0.81116558 0.        ]
 [0.79256524 0.         0.        ]
 [1.03781913 1.76693437 0.        ]
 [0.         0.72310602 0.8392368 ]
 [0.50389845 0.         0.        ]
 [0.         0.         0.87100308]
 [0.         0.         0.71410833]
 [0.         0.         1.91907899]
 [0.29084097 1.27046649 0.        ]
 [0.         1.07364684 0.        ]
 [0.08984546 0.56398505 0.38222671]
 [0.75045001 0.42510528 0.88144098]
 [0.5933376  0.45860744 0.36628793]]


In [18]:
names = np.array([['Aakash', 'Swara', 'Swaroop'],[ 'Aakash', 'Swaroop', 'Swara'],['Swara','JDK','Aakash']])

print(names)


[['Aakash' 'Swara' 'Swaroop']
 ['Aakash' 'Swaroop' 'Swara']
 ['Swara' 'JDK' 'Aakash']]


Concatenate of 2 Arrays

In [19]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([1,2,3,4,5])

arr3=np.concatenate((arr1,arr2))
print(arr3)
print(type(arr3))
arr3

[1 2 3 4 5 1 2 3 4 5]
<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [20]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5,6]])

# Join along rows (axis=0)
result = np.concatenate((arr1, arr2), axis=0)
print(result)


[[1 2]
 [3 4]
 [5 6]]


In [21]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5], [6]])

# Join along rows (axis=0)
result = np.concatenate((arr1, arr2), axis=1)
print(result)

[[1 2 5]
 [3 4 6]]


In [22]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([1,2,3,4,5])
result1=np.stack((arr1, arr2),axis=0)
result2=np.stack((arr1, arr2),axis=1)
print(result1)
print(result2)

[[1 2 3 4 5]
 [1 2 3 4 5]]
[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]

[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]


# <span style='color:red'> Vertical Stack and Horizontal Stack</span>

In [23]:
print(np.vstack((arr1, arr2)))
print(np.hstack((arr1, arr2)))

[[1 2 3 4 5]
 [1 2 3 4 5]]
[1 2 3 4 5 1 2 3 4 5]


# Spliting

In [24]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)
result = np.split(arr, 3)
print(result)
print(type(result))


[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>


In [25]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
result = np.split(arr, 3, axis=0)
print(arr)
print(result)

[[1 2]
 [3 4]
 [5 6]]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = np.hsplit(arr, 3)
print(result)

result1 = np.vsplit(arr, 2)
print(result1)


[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
[array([[1, 2, 3]]), array([[4, 5, 6]])]
