In [336]:
import numpy as np
arr=np.random.randn(8)
arr

array([-0.30053119, -0.13236409, -1.18755532, -0.3235815 , -0.04611789,
       -0.36660561, -1.20071069, -0.63875251])

In [337]:
np.sign(arr)

array([-1., -1., -1., -1., -1., -1., -1., -1.])

In [338]:
np.abs(arr)

array([0.30053119, 0.13236409, 1.18755532, 0.3235815 , 0.04611789,
       0.36660561, 1.20071069, 0.63875251])

In [339]:
x=np.random.randn(5)
y=np.random.randn(5)
print(x)
print(y)

[-0.46035138  1.11456276  1.19066773 -0.37168878  1.73113168]
[-0.05170732 -0.6368257   0.01416724 -0.03824731 -0.48351818]


In [340]:
np.maximum(x,y)

array([-0.05170732,  1.11456276,  1.19066773, -0.03824731,  1.73113168])

In [341]:
x=np.array([1,2,3,4,5])
y=np.array([6,7,8,9,10])

np.minimum(x,y)

array([1, 2, 3, 4, 5])

In [342]:
arr=np.array([2,3,4,np.nan,5])
arr*2

array([ 4.,  6.,  8., nan, 10.])

In [343]:
arr = np.random.randn(100)

(arr > 0).sum() # Number of positive values

48

# Summation of only positive numbers in array.
np.where(arr < 0, 0, arr).sum()

44.50560783530728

44.50560783530728

In [344]:
arr=np.array([[3,1,7],[6,4,5]])
print(arr)
sortd_arr=np.sort(arr)
print(sortd_arr)

colmn_arr=np.sort(arr,axis=0)
print(colmn_arr)

[[3 1 7]
 [6 4 5]]
[[1 3 7]
 [4 5 6]]
[[3 1 5]
 [6 4 7]]


**Raw wise Descending**

In [345]:
darr=np.sort(arr,axis=1)[:,::-1]
print(darr)

[[7 3 1]
 [6 5 4]]


**Column wise Descending**

In [346]:
darr=np.sort(arr,axis=0)[:,::-1]
print(darr)

[[5 1 3]
 [7 4 6]]


In [347]:
arr=np.zeros((1,6,2))
arr


array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [348]:
np.ravel(arr)
#ravel change dimension into one dim.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Linspace give us equle intervel number by defied range**

In [349]:
np.linspace(3,10,10)


array([ 3.        ,  3.77777778,  4.55555556,  5.33333333,  6.11111111,
        6.88888889,  7.66666667,  8.44444444,  9.22222222, 10.        ])

In [350]:
arr=np.array([[1,2,5,4,5],[7,5,4,2,5],[4,6,2,1,2]])
print(arr)

[[1 2 5 4 5]
 [7 5 4 2 5]
 [4 6 2 1 2]]


In [351]:
np.sum(arr,axis=0)

array([12, 13, 11,  7, 12])

In [352]:
np.sum(arr,axis=1)

array([17, 23, 15])

**We can print all array values by using flat whose make all values in flat line series**

In [353]:
x=arr.flat


In [354]:
for i in x:
    print(i)

1
2
5
4
5
7
5
4
2
5
4
6
2
1
2


In [355]:
arr=np.array([10,2,3,4,7,6,5,8,9,1])
print(arr[arr.argmax()])
print(arr[arr.argmin()])
#its give only max,min index position

10
1


In [356]:
print(arr.max())

10


**-------------------------------------------------------------------------------------------------------------------------------------------**

In [357]:
x=np.ones((4,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [358]:
x=np.arange(10,51)
x1=x

In [359]:
arr=np.random.randint(0,21,size=5) # the give random number generator between 0 and 21 total random 5
arr

array([ 5, 12, 11, 16,  7], dtype=int32)

In [360]:
arr=np.random.randint(0,10)
arr

5

In [361]:
arr=np.random.randint(0,11,size=(3,3))
arr

array([[ 7,  5,  9],
       [10,  4,  6],
       [ 2,  8,  4]], dtype=int32)