In [150]:
import numpy as np
arr=np.random.randn(8)
arr

array([-0.51405195,  0.22966604,  1.50403566,  1.60773772,  0.51311917,
       -0.91222198, -0.61827578, -0.42379735])

In [151]:
np.sign(arr)

array([-1.,  1.,  1.,  1.,  1., -1., -1., -1.])

In [152]:
np.abs(arr)

array([0.51405195, 0.22966604, 1.50403566, 1.60773772, 0.51311917,
       0.91222198, 0.61827578, 0.42379735])

In [153]:
x=np.random.randn(5)
y=np.random.randn(5)
print(x)
print(y)

[ 0.24059727 -0.89622734  1.14094739  0.0620396   0.86133132]
[-0.22586527  0.72930612  2.01861898  0.04572826 -0.39587171]


In [154]:
np.maximum(x,y)

array([0.24059727, 0.72930612, 2.01861898, 0.0620396 , 0.86133132])

In [155]:
x=np.array([1,2,3,4,5])
y=np.array([6,7,8,9,10])

np.minimum(x,y)

array([1, 2, 3, 4, 5])

In [156]:
arr=np.array([2,3,4,np.nan,5])
arr*2

array([ 4.,  6.,  8., nan, 10.])

In [157]:
arr = np.random.randn(100)

(arr > 0).sum() # Number of positive values

48

# Summation of only positive numbers in array.
np.where(arr < 0, 0, arr).sum()

44.50560783530728

44.50560783530728

In [158]:
arr=np.array([[3,1,7],[6,4,5]])
print(arr)
sortd_arr=np.sort(arr)
print(sortd_arr)

colmn_arr=np.sort(arr,axis=0)
print(colmn_arr)

[[3 1 7]
 [6 4 5]]
[[1 3 7]
 [4 5 6]]
[[3 1 5]
 [6 4 7]]


**Raw wise Descending**

In [159]:
darr=np.sort(arr,axis=1)[:,::-1]
print(darr)

[[7 3 1]
 [6 5 4]]


**Column wise Descending**

In [160]:
darr=np.sort(arr,axis=0)[:,::-1]
print(darr)

[[5 1 3]
 [7 4 6]]


In [161]:
arr=np.zeros((1,6,2))
arr


array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [162]:
np.ravel(arr)
#ravel change dimension into one dim.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Linspace give us equle intervel number by defied range**

In [163]:
np.linspace(3,10,10)


array([ 3.        ,  3.77777778,  4.55555556,  5.33333333,  6.11111111,
        6.88888889,  7.66666667,  8.44444444,  9.22222222, 10.        ])

In [164]:
arr=np.array([[1,2,5,4,5],[7,5,4,2,5],[4,6,2,1,2]])
print(arr)

[[1 2 5 4 5]
 [7 5 4 2 5]
 [4 6 2 1 2]]


In [165]:
np.sum(arr,axis=0)

array([12, 13, 11,  7, 12])

In [166]:
np.sum(arr,axis=1)

array([17, 23, 15])

**We can print all array values by using flat whose make all values in flat line series**

In [167]:
x=arr.flat


In [168]:
for i in x:
    print(i)

1
2
5
4
5
7
5
4
2
5
4
6
2
1
2


In [175]:
arr=np.array([10,2,3,4,7,6,5,8,9,1])
print(arr[arr.argmax()])
print(arr[arr.argmin()])
#its give only max,min index position

10
1


In [170]:
print(arr.max())

10


**-------------------------------------------------------------------------------------------------------------------------------------------**

In [171]:
x=np.ones((4,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [172]:
x=np.arange(10,51)
x1=x