Q. Get top 4 value from giving array below

In [12]:
import numpy as np
x=[[10,20,15],
    [40,50,35],
    [25,30,45],
    [50,60,70]]

x1=np.array(x)
print(x1)

x2=x1.flatten()
x3=np.sort(x2)
print(x3)
x4 = x3[-4:]
print(x4)
x5=np.unique(x4)
print(x5)



[[10 20 15]
 [40 50 35]
 [25 30 45]
 [50 60 70]]
[10 15 20 25 30 35 40 45 50 50 60 70]
[50 50 60 70]
[50 60 70]


Q. Find Odd value from the giving array below and make square values.

In [13]:
x1=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

print(x1)

x1=np.where(x1 % 2 !=0,x1**2,x1)
print(x1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  9]
 [ 4 25  6]
 [49  8 81]]


Q. Create 4*2 integers array from 0 to 7 and print ?

In [14]:
arr=np.arange(0,8).reshape((4,2))
print(arr)
print(arr.shape)
print(arr.ndim)
print(len(arr)) # number of available rows in the array
print(arr.size) # number of available elements in the array

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
(4, 2)
2
4
8


Q. Create a 5*2 integer array from a range between 100 and 200 with difference between 10 ?

In [15]:
arr=np.arange(100,200,10).reshape((5,2))
print(arr)


[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


Q. Return 3rd column of the array ?

In [16]:
arr=np.array([[11,22,33],[44,55,66],[77,88,99]])
print(arr)

print(arr[:,2]) # if you want to access the columns of the array
print(arr[1,:]) # if you want to access the rows of the array
print(arr[2,2])#if you want to get a particular positional value
print(arr[2][2])# both are same 


[[11 22 33]
 [44 55 66]
 [77 88 99]]
[33 66 99]
[44 55 66]
99
99
