In [2]:
import numpy as np
x=[[10,20,15],
    [40,50,35],
    [25,30,45],
    [50,60,70]]

x1=np.array(x)
print(x1)

x2=x1.flatten()
x3=np.sort(x2)
print(x3)
x4 = x3[-4:]
print(x4)
x5=np.unique(x4)
print(x5)



[[10 20 15]
 [40 50 35]
 [25 30 45]
 [50 60 70]]
[10 15 20 25 30 35 40 45 50 50 60 70]
[50 50 60 70]
[50 60 70]


In [4]:
x1=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(x1)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
